language: java
before_install:
  - chmod +x mvnw
jdk: openjdk15
deploy:
  provider: releases
  api_key:
    secure: QQZUcfOdwWkZJjVNq8MDKCOIYc0ZSyvW5wVA8IZ/4BXZUrl2qmg4n9jiuIdJn74oFcTFgOStVvR6P+NMtHG7TpQxij6gK5cKDsELTKNbKkf6fTF5QyMxXpmuE2nV7kJm7gX4fPYgXhFS8afPNirrh5R9jpRuq13NqvRxiplReDSyK751s/e+Cayt0TvsWm8ZLbDFLJwk65UHUnX3xlWXMj1lxex7OZq/Ke4x60fg5sXegKcVVxTtxjhR9iilhJcwhj2X7tnrZqzQlP+HnoPpAaQdK+QI2/P7W953MkwCcv/X3lCFVJ3r37tfjmuSgX+/9QHBEuNfSFxYwOjaUmnZCFVOVY0Soxj1q7T72UoG7/HhHXzMNjEJNYlppz4PWuguLyXMwqQCFRBLmMIR8NsIbu/mr+GLVIu3PhvKIjbDMMV4M9kerjEn6oX/j1BSiAX1r6ZUCNkGHlRLqpPkljuP3dMXcZ3JggiUgqCNE8MFEVUzoeXNUp4FUNqtqDOMVl/8XYCGEMHb+l06rPhELISSm4NJ8IlpJE4qLCfpF32qwj36mvyzoD3NpR4EnfYF6npm9OfjFKf6ANmEMYXN9574rLyClb8q2Iljq5CVKNNbx9uXSbbhdJgksaAt0xJpiCel+tzAF5ZXYOIlZIfv+/IE+Ntcxz/QFAUwEPEiDu5rVV0=
  file: target/vlc-bot.jar
  skip_cleanup: true
  tag: 0.0.3
  on:
    branch: master