language: java
before_install:
  - chmod +x mvnw
jdk: openjdk15
deploy:
  provider: releases
  api_key:
    secure: "gvwCYcWo8t5K9l1d9wnaswEn+pcWT/ow+AVASpAA2/Pg+QwIBiebTVEib6GGDKT9b9QxPpeda2oN8Dhon0LAhYwbn51enk1MoYJsZ9pg4JunYSzEWvRY8RhPN2R/U0FFgjxCbQfY4CBR/EFsds/KTl6XHjVyrcsLkAem8CCmZa6ZhcZZyTPrl+7/ltvPqmzWIRtZazDCrtcUfGM4asW5gS9Gb+O9/IZgNvCN352Mddl8QwICpQ9u5U00Blzt80hwrZh+dL/1GKxUtw8uXkdIBymZk7NEaSeNa3R568FN7ftfCfXaUkfSjWWsC+wyd9EB+jIkczyFl8ogHTVTDB9ZZkntH0QEN7wEgk35tZ0M8Sh/EYMWIEIF6WiTWpTQ1ORvMr85RRzGmEhW9tCkVoKRURcsq0OwzKVS8taIt59/VoIlsc94bdXbjwW7wN1tYnp2B+J38SJ7eGBoNzkEKSoEK8Mb3w2lAALLIxJA28JCSmJ1GASsW98REvmPUJkPQQsPggDYYldmqt9GoXBe6mnqFa27Bvz9Ki7Uq8CTaQPJvjIRL0BEiC4LtWqmiwXvLQxglcex9/GREFwE0twdGkHF4CSj3jMGBeLxK2dzjj+PSA+WHKSDwAmx7WiWLjgXtvOvQ4g8d+Doi0GpJ+ZzM9RWb3nKGCKkCjU3j2gl9dp5Kw4="
  file: target/vlc-bot.jar
  skip_cleanup: true
  on:
    tags: true